name: staging deploy

on:
  push:
    branches: 
      - staging

jobs:
  deploy-staging:

    runs-on: ubuntu-latest
    needs: build-and-test 
    steps:
    - uses: actions/checkout@v4
    - run: npm i  